*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 19.10.2017 at 10:56:16
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVMSS_SIGN_DOC..................................*
FORM GET_DATA_ZVMSS_SIGN_DOC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTMSS_SIGN_DOC WHERE
(VIM_WHERETAB) .
    CLEAR ZVMSS_SIGN_DOC .
ZVMSS_SIGN_DOC-MANDT =
ZTMSS_SIGN_DOC-MANDT .
ZVMSS_SIGN_DOC-AWART =
ZTMSS_SIGN_DOC-AWART .
ZVMSS_SIGN_DOC-FIELD_05 =
ZTMSS_SIGN_DOC-FIELD_05 .
ZVMSS_SIGN_DOC-NEED_BEGDA =
ZTMSS_SIGN_DOC-NEED_BEGDA .
ZVMSS_SIGN_DOC-NEED_ENDDA =
ZTMSS_SIGN_DOC-NEED_ENDDA .
ZVMSS_SIGN_DOC-NEED_DAYS_COUNT =
ZTMSS_SIGN_DOC-NEED_DAYS_COUNT .
ZVMSS_SIGN_DOC-FIELD_07 =
ZTMSS_SIGN_DOC-FIELD_07 .
ZVMSS_SIGN_DOC-FIELD_08 =
ZTMSS_SIGN_DOC-FIELD_08 .
    SELECT SINGLE * FROM T554S WHERE
MOABW = '33' AND
SUBTY = ZTMSS_SIGN_DOC-AWART AND
ENDDA = '99991231' .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVMSS_SIGN_DOC-ATEXT =
T554T-ATEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVMSS_SIGN_DOC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVMSS_SIGN_DOC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVMSS_SIGN_DOC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVMSS_SIGN_DOC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTMSS_SIGN_DOC WHERE
  AWART = ZVMSS_SIGN_DOC-AWART .
    IF SY-SUBRC = 0.
    DELETE ZTMSS_SIGN_DOC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTMSS_SIGN_DOC WHERE
  AWART = ZVMSS_SIGN_DOC-AWART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTMSS_SIGN_DOC.
    ENDIF.
ZTMSS_SIGN_DOC-MANDT =
ZVMSS_SIGN_DOC-MANDT .
ZTMSS_SIGN_DOC-AWART =
ZVMSS_SIGN_DOC-AWART .
ZTMSS_SIGN_DOC-FIELD_05 =
ZVMSS_SIGN_DOC-FIELD_05 .
ZTMSS_SIGN_DOC-NEED_BEGDA =
ZVMSS_SIGN_DOC-NEED_BEGDA .
ZTMSS_SIGN_DOC-NEED_ENDDA =
ZVMSS_SIGN_DOC-NEED_ENDDA .
ZTMSS_SIGN_DOC-NEED_DAYS_COUNT =
ZVMSS_SIGN_DOC-NEED_DAYS_COUNT .
ZTMSS_SIGN_DOC-FIELD_07 =
ZVMSS_SIGN_DOC-FIELD_07 .
ZTMSS_SIGN_DOC-FIELD_08 =
ZVMSS_SIGN_DOC-FIELD_08 .
    IF SY-SUBRC = 0.
    UPDATE ZTMSS_SIGN_DOC .
    ELSE.
    INSERT ZTMSS_SIGN_DOC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVMSS_SIGN_DOC-UPD_FLAG,
STATUS_ZVMSS_SIGN_DOC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVMSS_SIGN_DOC.
  SELECT SINGLE * FROM ZTMSS_SIGN_DOC WHERE
AWART = ZVMSS_SIGN_DOC-AWART .
ZVMSS_SIGN_DOC-MANDT =
ZTMSS_SIGN_DOC-MANDT .
ZVMSS_SIGN_DOC-AWART =
ZTMSS_SIGN_DOC-AWART .
ZVMSS_SIGN_DOC-FIELD_05 =
ZTMSS_SIGN_DOC-FIELD_05 .
ZVMSS_SIGN_DOC-NEED_BEGDA =
ZTMSS_SIGN_DOC-NEED_BEGDA .
ZVMSS_SIGN_DOC-NEED_ENDDA =
ZTMSS_SIGN_DOC-NEED_ENDDA .
ZVMSS_SIGN_DOC-NEED_DAYS_COUNT =
ZTMSS_SIGN_DOC-NEED_DAYS_COUNT .
ZVMSS_SIGN_DOC-FIELD_07 =
ZTMSS_SIGN_DOC-FIELD_07 .
ZVMSS_SIGN_DOC-FIELD_08 =
ZTMSS_SIGN_DOC-FIELD_08 .
    SELECT SINGLE * FROM T554S WHERE
MOABW = '33' AND
SUBTY = ZTMSS_SIGN_DOC-AWART AND
ENDDA = '99991231' .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVMSS_SIGN_DOC-ATEXT =
T554T-ATEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVMSS_SIGN_DOC-ATEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVMSS_SIGN_DOC-ATEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVMSS_SIGN_DOC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVMSS_SIGN_DOC-AWART TO
ZTMSS_SIGN_DOC-AWART .
MOVE ZVMSS_SIGN_DOC-MANDT TO
ZTMSS_SIGN_DOC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTMSS_SIGN_DOC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTMSS_SIGN_DOC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTMSS_SIGN_DOC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVMSS_SIGN_DOC USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTMSS_SIGN_DOC-MANDT =
ZVMSS_SIGN_DOC-MANDT .
ZTMSS_SIGN_DOC-AWART =
ZVMSS_SIGN_DOC-AWART .
ZTMSS_SIGN_DOC-FIELD_05 =
ZVMSS_SIGN_DOC-FIELD_05 .
ZTMSS_SIGN_DOC-NEED_BEGDA =
ZVMSS_SIGN_DOC-NEED_BEGDA .
ZTMSS_SIGN_DOC-NEED_ENDDA =
ZVMSS_SIGN_DOC-NEED_ENDDA .
ZTMSS_SIGN_DOC-NEED_DAYS_COUNT =
ZVMSS_SIGN_DOC-NEED_DAYS_COUNT .
ZTMSS_SIGN_DOC-FIELD_07 =
ZVMSS_SIGN_DOC-FIELD_07 .
ZTMSS_SIGN_DOC-FIELD_08 =
ZVMSS_SIGN_DOC-FIELD_08 .
    SELECT SINGLE * FROM T554S WHERE
MOABW = '33' AND
SUBTY = ZTMSS_SIGN_DOC-AWART AND
ENDDA = '99991231' .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVMSS_SIGN_DOC-ATEXT =
T554T-ATEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVMSS_SIGN_DOC-ATEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVMSS_SIGN_DOC-ATEXT .
    ENDIF.
ENDFORM.
